version: '3.8'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    container_name: es_etl
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
    ports:
      - 9200:9200
    networks:
      - elastic_etl


  db:
    build:
      context: .
      target: database
    image: pgdb:16
    container_name: db
    restart: always
    volumes:
      - $HOME/postgresql/data:/var/lib/postgresql/data
    env_file:
      - "./etl/.env"
    networks:
      - elastic_etl


  etl:
    build:
      context: .
      target: service
    image: etl:latest
    container_name: etl_script_test
    restart: always
    networks:
      - elastic_etl
    depends_on:
      - db
      - es
    env_file:
      - "./etl/.env"


networks:
  elastic_etl:
    driver: bridge