etl:
  postgres:
    dsn:
      dbname: ${DB_NAME}
      user: ${DB_USER}
      password: ${DB_PASSWORD}
      host: ${DB_HOST}
      port: ${DB_PORT}
      options: "-c search_path=content"


  es:
    default_host:
      host: ${ES_HOST}
      port: ${ES_PORT}
    index_name: ${ES_INDEX_NAME}
    index_config: "index_config.json"

  state_file_name: "state.yaml"
  fetch_delay: 0.1
  log_status_period: 180