etl:
  postgres:
    dsn:
      dbname: movies_database
      user: app
      password: 123qwe
      host: '0.0.0.0'
      port: 5432
      options: "-c search_path=content"


  es:
    default_host:
      host: 'http://0.0.0.0'
      port: 9200
    index_name: movies
    index_config: "index.json"

  state_file_name: "state.yaml"
  fetch_delay: 0.1
  log_status_period: 180
